### ISSUE TITLE
Crash when playing spx-biocoresystem.it

### ISSUE THREAD

**Issue by Mohamed00** [8bitbubsy/it2play#4]
I noticed that when playing this module, https://api.modarchive.org/downloads.php?moduleid=193837#spx-biocoresystem.it, it2play crashes consistently around order 61. There's also another crash that can happen around order 28, but that seems to be more rare. Tested with it2play.exe compiled under Visual Studio 2022.

**Comment by 8bitbubsy** [comment]
Hi, thanks for reporting the issue! I have narrowed it down to being a problem with it2play on pingpong/bidi-loops played at an extremely high pitch. I am currently trying to find out if I forgot to add a special test case in the loop wrap handling. I'll come back to you eventually.

**Comment by 8bitbubsy** [comment]
OK I fixed this issue now!

**Comment by Mohamed00** [comment]
Confirmed, the module plays without crashes. Thanks!
